name: "Docker Build Custom"

on:
  workflow_dispatch:
    inputs:
      nom:
        description: "Ton nom"
        required: true
        type: string

      version:
        description: "Version de l'image (ex: 1.0.0)"
        required: true
        type: string
        default: "1.0.0"

      image:
        description: "Nom de l'image Docker"
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Afficher les informations saisies
        run: |
          echo "👤 Nom       : ${{ inputs.nom }}"
          echo "🏷️  Version   : ${{ inputs.version }}"
          echo "🐳 Image     : ${{ inputs.image }}"

      - name: Connexion à ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: ./services/${{ inputs.image }}
          file: ./services/${{ inputs.image }}/Dockerfile
          push: true
          tags: |
            ghcr.io/donassongui/${{ inputs.image }}:${{ inputs.version }}
            ghcr.io/donassongui/${{ inputs.image }}:latest

      - name: Nettoyer le nom de l'image
        id: clean
        run: |
          # Remplace les espaces par des tirets et met en minuscules
          CLEAN_IMAGE=$(echo "${{ inputs.image }}" | tr ' ' '-' | tr '[:upper:]' '[:lower:]')
          echo "image=$CLEAN_IMAGE" >> $GITHUB_OUTPUT
      
      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: ./services/${{ steps.clean.outputs.image }}
          file: ./services/${{ steps.clean.outputs.image }}/Dockerfile
          push: true
          tags: |
            ghcr.io/donassongui/${{ steps.clean.outputs.image }}:${{ inputs.version }}
            ghcr.io/donassongui/${{ steps.clean.outputs.image }}:latest
